import { pgEnum } from "drizzle-orm/pg-core";

export const ownershipTypeEnum = pgEnum("ownership_type", [
  "nonprofit",
  "for_profit",
  "government",
  "unknown",
]);

export const crmTypeEnum = pgEnum("crm_type", [
  "ghl",
  "hubspot",
  "salesforce",
  "pipedrive",
  "zoho",
  "close",
  "dynamics",
  "other",
]);

export const signalTypeEnum = pgEnum("signal_type", [
  "depreciation_flag",
  "con_filed",
  "con_approved",
  "grant_awarded",
  "bond_issuance",
  "bond_issued",
  "rfp_posted",
  "hcris_depreciation_spike",
  "high_utilization",
  "equipment_age_7yr",
  "adverse_event_spike",
  "sec_capex_flag",
  "construction_permit",
  "leadership_change",
  "service_line_expansion",
  "job_posting",
  "news_expansion",
  "eol_equipment",
  "accreditation_renewal",
  "compliance_citation",
  "nih_grant",
  "clinical_trial",
  "fiscal_year_end",
  "system_signal_propagated",
  "financial_health",
  "capital_investment",
  "workforce_expansion",
  "hospital_operator",
  // ── Medintel warehouse signals ──────────────────────────────────────────
  // Emitted by services/medintelSignalScorer.ts from the medintel.* warehouse.
  "chow_recent",         // Hospital/SNF change-of-ownership in the last 18 months
  "pe_takeover",         // Private-equity ownership recorded in PECOS
  "reit_takeover",       // REIT ownership recorded in PECOS
  "aip_infra_spend",     // ACO has Advance Investment Payment dollars earmarked for infrastructure
  "cmmi_state_launch",   // A CMMI Innovation Center model is active in the facility's state
  "psi11_outlier",       // AHRQ PSI-11 rate above national average
  "chain_acquisition",   // Owner flagged as chain-home-office controls multiple facilities
]);

export const contactStatusEnum = pgEnum("contact_status", [
  "unverified",
  "verified",
  "bounced",
  "unsubscribed",
  "do_not_contact",
]);

export const outreachChannelEnum = pgEnum("outreach_channel", [
  "email",
  "linkedin",
  "phone",
  "both",
]);

export const enrollmentStatusEnum = pgEnum("enrollment_status", [
  "active",
  "paused",
  "replied",
  "complete",
  "unsubscribed",
  "bounced",
]);

export const draftStatusEnum = pgEnum("draft_status", [
  "pending",
  "approved",
  "sent",
  "skipped",
  "rejected",
]);

// ─── v2.0 — Opportunity Inbox ────────────────────────────────────────────────
export const buyerRoleEnum = pgEnum("buyer_role", [
  "clinical_champion",
  "economic_buyer",
  "procurement_gatekeeper",
  "technical_evaluator",
  "end_user",
  "executive_sponsor",
  "finance_approver",
  "compliance_reviewer",
]);

export const opportunityStatusEnum = pgEnum("opportunity_status", [
  "detected",        // auto-generated by opportunityGenerator
  "rep_reviewed",    // rep has looked at the card
  "qualified",       // rep marked Pursue
  "bid_submitted",   // pushed to GHL as a pending draft
  "won",             // closed-won (rep-marked, not platform-detected)
  "lost",            // closed-lost
  "dormant",         // snoozed > 90 days with no movement
]);

export const opportunityActionTypeEnum = pgEnum("opportunity_action_type", [
  "pursue",
  "skip",
  "snooze",
  "note",
  "push_to_ghl",
  "qualify",
  "disqualify",
  "won",
  "lost",
]);

export const syncStatusEnum = pgEnum("sync_status", [
  "pending",
  "running",
  "complete",
  "failed",
  "partial",
]);

export const reportStatusEnum = pgEnum("report_status", [
  "queued",
  "running",
  "complete",
  "failed",
]);

export const planTierEnum = pgEnum("plan_tier", [
  "starter",
  "growth",
  "enterprise",
  "internal",
]);

export const enrichmentSourceEnum = pgEnum("enrichment_source", [
  "npi_registry",
  "doximity",
  "website_scrape",
  "cms_billing",
  "professional_directory",
  "clinicaltrials",
  "nih_reporter",
  "propublica_990",
  "hcris",
  "con_filing",
  "radiation_registry",
  "apollo",
  "netrows",
  "zerobounce",
  "bouncer",
  "twilio",
  "people_data_labs",
  "zoominfo",
  "definitive_hc",
  "openpermit",
]);

export const FREE_ENRICHMENT_SOURCES = [
  "npi_registry",
  "doximity",
  "website_scrape",
  "cms_billing",
  "professional_directory",
  "clinicaltrials",
  "nih_reporter",
  "propublica_990",
  "hcris",
  "con_filing",
  "radiation_registry",
] as const;

export const PAID_ENRICHMENT_SOURCES = [
  "apollo",
  "netrows",
  "zerobounce",
  "bouncer",
  "twilio",
  "people_data_labs",
  "zoominfo",
  "definitive_hc",
  "openpermit",
] as const;
